import {
  Snowflake, TreePine, Trash2, Wrench, Building2, Droplets, SprayCan, Briefcase,
  Zap, Pipette, Hammer, Home, PaintBucket, Wind, Boxes, Shield,
  Fence, LayoutGrid, CloudRain, Square, Bug, Truck, Layers, Plug,
  DoorOpen, KeyRound,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface ServicePromo {
  id: string;
  title: string;
  subtitle: string;
  audience: string;
  highlights: string[];
  cta?: string;
  icon: LucideIcon;
  accentClass: string;
  iconColorClass: string;
}

export const SERVICE_PROMOS: ServicePromo[] = [
  {
    id: 'snow-ice',
    title: 'Snow & Ice',
    subtitle: 'Strength in Every Storm',
    audience: 'Residential · Commercial · Municipal · Government · Strata',
    highlights: [
      'Reliable winter service with 24/7 response',
      'Plowing, salting, sanding & sidewalk clearing',
      'Property-management-friendly scheduling',
      'Environment Canada weather intelligence',
    ],
    icon: Snowflake,
    accentClass: 'bg-sky-100 dark:bg-sky-950/40',
    iconColorClass: 'text-sky-600',
  },
  {
    id: 'maintenance-repairs',
    title: 'Maintenance & Repairs',
    subtitle: 'Fast Fixes, Done Right',
    audience: 'Residential · Commercial · Rental · Property Management',
    highlights: [
      'General handyman repairs',
      'Same-day & emergency call-outs',
      'Preventative maintenance programs',
      'Single point of contact for all trades',
    ],
    icon: Wrench,
    accentClass: 'bg-red-100 dark:bg-red-950/40',
    iconColorClass: 'text-red-600',
  },
  {
    id: 'landscaping',
    title: 'Property Care & Landscaping',
    subtitle: 'Professional Lawn Care',
    audience: 'Residential · Commercial · Municipal · Government',
    highlights: [
      'Mowing, trimming, cleanups & weed control',
      'Fertilization, aeration & seeding',
      'Right-of-way / roadside maintenance',
      'Multi-unit & property management friendly',
    ],
    icon: TreePine,
    accentClass: 'bg-orange-100 dark:bg-orange-950/40',
    iconColorClass: 'text-orange-600',
  },
  {
    id: 'property-management',
    title: 'Property Management',
    subtitle: 'Full-Service Building Operations',
    audience: 'Multi-Unit · Strata · Commercial · Government · Rental',
    highlights: [
      'Coordinated service across all properties',
      'Vendor management & work order tracking',
      'Seasonal planning & preventative programs',
      'Tenant communication & documentation',
    ],
    icon: Building2,
    accentClass: 'bg-emerald-100 dark:bg-emerald-950/40',
    iconColorClass: 'text-emerald-600',
  },
  {
    id: 'electrical',
    title: 'Electrical',
    subtitle: 'Licensed & Code-Compliant',
    audience: 'Residential · Commercial · Industrial',
    highlights: [
      'Outlet, switch & fixture installations',
      'Panel upgrades & breaker replacement',
      'Lighting design & retrofits',
      'EV charger installation',
    ],
    icon: Zap,
    accentClass: 'bg-violet-100 dark:bg-violet-950/40',
    iconColorClass: 'text-violet-600',
  },
  {
    id: 'plumbing',
    title: 'Plumbing',
    subtitle: 'Leaks, Drains & Fixtures',
    audience: 'Residential · Commercial · Property Management',
    highlights: [
      'Leak repair & drain unclogging',
      'Faucet, toilet & water heater installs',
      'Pipe repair & replacement',
      'Emergency plumbing service',
    ],
    icon: Pipette,
    accentClass: 'bg-teal-100 dark:bg-teal-950/40',
    iconColorClass: 'text-teal-600',
  },
  {
    id: 'carpentry-renovations',
    title: 'Carpentry & Renovations',
    subtitle: 'Custom Builds & Remodels',
    audience: 'Residential · Commercial · Rental Properties',
    highlights: [
      'Kitchen & bathroom renovations',
      'Custom millwork, trim & cabinetry',
      'Framing, drywall & finishing',
      'Basement & suite buildouts',
    ],
    icon: Hammer,
    accentClass: 'bg-amber-100 dark:bg-amber-950/40',
    iconColorClass: 'text-amber-700',
  },
  {
    id: 'roofing-exteriors',
    title: 'Roofing & Exteriors',
    subtitle: 'Protect From the Top Down',
    audience: 'Residential · Commercial · Strata',
    highlights: [
      'Roof inspections, repairs & replacements',
      'Soffit, fascia & siding work',
      'Flashing & ventilation upgrades',
      'Storm-damage assessments',
    ],
    icon: Home,
    accentClass: 'bg-slate-200 dark:bg-slate-800/60',
    iconColorClass: 'text-slate-700',
  },
  {
    id: 'painting-finishing',
    title: 'Painting & Finishing',
    subtitle: 'Crisp, Lasting Finishes',
    audience: 'Residential · Commercial · Rental · Strata',
    highlights: [
      'Interior & exterior painting',
      'Drywall patching & priming',
      'Cabinet & trim refinishing',
      'Pressure-washed prep included',
    ],
    icon: PaintBucket,
    accentClass: 'bg-yellow-100 dark:bg-yellow-950/40',
    iconColorClass: 'text-yellow-600',
  },
  {
    id: 'cleaning',
    title: 'Cleaning Services',
    subtitle: 'Spotless Spaces, Every Time',
    audience: 'Residential · Commercial · Hospitality · Government',
    highlights: [
      'Move-in & move-out deep cleaning',
      'Airbnb, hotel & short-term rental turnover',
      'Office, school & shopping center cleaning',
      'Heavy-duty & post-renovation cleanup',
    ],
    icon: SprayCan,
    accentClass: 'bg-sky-100 dark:bg-sky-950/40',
    iconColorClass: 'text-sky-600',
  },
  {
    id: 'hvac',
    title: 'Heating, Ventilation & Air Conditioning',
    subtitle: 'Climate Comfort, Year-Round',
    audience: 'Residential · Commercial · Property Management',
    highlights: [
      'Furnace & A/C install, repair & service',
      'Duct cleaning & airflow balancing',
      'Thermostat upgrades (incl. smart)',
      'Seasonal tune-ups & filter programs',
    ],
    icon: Wind,
    accentClass: 'bg-rose-100 dark:bg-rose-950/40',
    iconColorClass: 'text-rose-600',
  },
  {
    id: 'concrete-masonry',
    title: 'Concrete & Masonry',
    subtitle: 'Solid Foundations & Surfaces',
    audience: 'Residential · Commercial · Municipal',
    highlights: [
      'Driveways, sidewalks & pads',
      'Steps, retaining walls & curbs',
      'Brick, block & stone repair',
      'Sealing, parging & resurfacing',
    ],
    icon: Boxes,
    accentClass: 'bg-gray-200 dark:bg-gray-800/60',
    iconColorClass: 'text-gray-700',
  },
  {
    id: 'security-smart-home',
    title: 'Security & Smart Home',
    subtitle: 'Protect & Automate',
    audience: 'Residential · Commercial · Multi-Unit',
    highlights: [
      'Camera & alarm system installs',
      'Smart locks, doorbells & sensors',
      'Wi-Fi, hubs & home automation',
      'Access control for businesses',
    ],
    icon: Shield,
    accentClass: 'bg-zinc-200 dark:bg-zinc-800/60',
    iconColorClass: 'text-zinc-800',
  },
  {
    id: 'fencing-decking',
    title: 'Fencing & Decking',
    subtitle: 'Outdoor Living & Privacy',
    audience: 'Residential · Commercial · Strata',
    highlights: [
      'Wood, vinyl & chain-link fencing',
      'Custom decks, railings & pergolas',
      'Repairs, staining & sealing',
      'Gates & privacy screens',
    ],
    icon: Fence,
    accentClass: 'bg-orange-100 dark:bg-orange-950/40',
    iconColorClass: 'text-orange-800',
  },
  {
    id: 'junk-removal',
    title: 'Junk Removal',
    subtitle: 'Fast & Reliable Pickup',
    audience: 'Residential · Commercial · Property Management',
    highlights: [
      'Tenant move-outs & unit cleanouts',
      'Bin overflow & bulky-item pickup',
      'Renovation debris & contractor cleanup',
      'Eco-friendly disposal',
    ],
    icon: Trash2,
    accentClass: 'bg-orange-100 dark:bg-orange-950/40',
    iconColorClass: 'text-orange-700',
  },
  {
    id: 'power-washing',
    title: 'Power Washing',
    subtitle: 'Restore Curb Appeal',
    audience: 'Residential · Commercial · Municipal · Strata',
    highlights: [
      'Driveways, walkways & parking areas',
      'Building exteriors, siding & decks',
      'Garbage bin & dumpster area cleaning',
      'Pre-paint surface preparation',
    ],
    icon: Droplets,
    accentClass: 'bg-cyan-100 dark:bg-cyan-950/40',
    iconColorClass: 'text-cyan-600',
  },
  {
    id: 'tiling-flooring',
    title: 'Tiling & Flooring',
    subtitle: 'Floors That Last',
    audience: 'Residential · Commercial · Rental',
    highlights: [
      'Tile, vinyl, laminate & hardwood',
      'Subfloor prep & leveling',
      'Backsplashes & shower surrounds',
      'Repair & replacement work',
    ],
    icon: LayoutGrid,
    accentClass: 'bg-amber-100 dark:bg-amber-950/40',
    iconColorClass: 'text-amber-700',
  },
  {
    id: 'gutter-cleaning',
    title: 'Gutter Cleaning & Repair',
    subtitle: 'Keep Water Flowing Away',
    audience: 'Residential · Commercial · Strata',
    highlights: [
      'Seasonal gutter cleaning',
      'Downspout repair & extensions',
      'Leaf guard installation',
      'Flashing & seam resealing',
    ],
    icon: CloudRain,
    accentClass: 'bg-lime-100 dark:bg-lime-950/40',
    iconColorClass: 'text-lime-700',
  },
  {
    id: 'window-cleaning',
    title: 'Window Cleaning',
    subtitle: 'Streak-Free Shine',
    audience: 'Residential · Commercial · Hospitality',
    highlights: [
      'Interior & exterior windows',
      'Screen & track cleaning',
      'Storefronts & high-rise (low-rise reach)',
      'Post-construction window detail',
    ],
    icon: Square,
    accentClass: 'bg-sky-100 dark:bg-sky-950/40',
    iconColorClass: 'text-sky-700',
  },
  {
    id: 'pest-control',
    title: 'Pest Control',
    subtitle: 'Safe, Targeted Treatments',
    audience: 'Residential · Commercial · Hospitality',
    highlights: [
      'Insect & rodent treatments',
      'Wasp & ant nest removal',
      'Preventative recurring service',
      'Eco-friendly options available',
    ],
    icon: Bug,
    accentClass: 'bg-amber-100 dark:bg-amber-950/40',
    iconColorClass: 'text-amber-800',
  },
  {
    id: 'moving-hauling',
    title: 'Moving & Hauling',
    subtitle: 'Local Moves & Deliveries',
    audience: 'Residential · Commercial · Property Management',
    highlights: [
      'Apartment & house moves',
      'Office relocations',
      'Furniture & appliance delivery',
      'Loading & unloading help',
    ],
    icon: Truck,
    accentClass: 'bg-purple-100 dark:bg-purple-950/40',
    iconColorClass: 'text-purple-600',
  },
  {
    id: 'insulation-drywall',
    title: 'Insulation & Drywall',
    subtitle: 'Comfort, Quiet & Efficiency',
    audience: 'Residential · Commercial · Renovation',
    highlights: [
      'Batt, blown-in & spray-foam insulation',
      'Drywall hang, mud, tape & sand',
      'Repair, patching & texturing',
      'Soundproofing assemblies',
    ],
    icon: Layers,
    accentClass: 'bg-red-100 dark:bg-red-950/40',
    iconColorClass: 'text-red-700',
  },
  {
    id: 'appliance-repair',
    title: 'Appliance Install & Repair',
    subtitle: 'Keep It Running',
    audience: 'Residential · Rental · Hospitality',
    highlights: [
      'Washer, dryer, dishwasher service',
      'Stove, fridge & range hood install',
      'Diagnostics & part replacement',
      'New appliance hookup',
    ],
    icon: Plug,
    accentClass: 'bg-teal-100 dark:bg-teal-950/40',
    iconColorClass: 'text-teal-700',
  },
  {
    id: 'garage-doors',
    title: 'Garage Doors',
    subtitle: 'Smooth Open & Close',
    audience: 'Residential · Commercial · Strata',
    highlights: [
      'Spring, cable & roller repair',
      'Opener install & programming',
      'Panel & weather-seal replacement',
      'Tune-ups & safety inspections',
    ],
    icon: DoorOpen,
    accentClass: 'bg-slate-200 dark:bg-slate-800/60',
    iconColorClass: 'text-slate-600',
  },
  {
    id: 'locksmith',
    title: 'Locksmith Services',
    subtitle: 'Lockouts, Rekey & Hardware',
    audience: 'Residential · Commercial · Property Management',
    highlights: [
      'Emergency lockout assistance',
      'Rekey & master-key systems',
      'Deadbolt & smart-lock installs',
      'Commercial door hardware',
    ],
    icon: KeyRound,
    accentClass: 'bg-blue-100 dark:bg-blue-950/40',
    iconColorClass: 'text-blue-700',
  },
  {
    id: 'other',
    title: 'Custom & Specialty Services',
    subtitle: 'Tailored to Your Needs',
    audience: 'All Property Types',
    highlights: [
      'Flexible service packages',
      'One-time or recurring scheduling',
      'Custom scoping & competitive pricing',
      'Single trusted team for all services',
    ],
    icon: Briefcase,
    accentClass: 'bg-slate-100 dark:bg-slate-900/40',
    iconColorClass: 'text-slate-600',
  },
];
