
ALTER TABLE public.products_services
  ADD COLUMN IF NOT EXISTS book_service_as TEXT NOT NULL DEFAULT 'Job',
  ADD COLUMN IF NOT EXISTS service_duration_minutes INTEGER NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS allow_customer_quantity BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS min_quantity INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS max_quantity INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS available_on_quotes BOOLEAN NOT NULL DEFAULT true;
