
ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS customer_type text NOT NULL DEFAULT 'Residential',
  ADD COLUMN IF NOT EXISTS account_type text NOT NULL DEFAULT 'Individual',
  ADD COLUMN IF NOT EXISTS company_legal_name text,
  ADD COLUMN IF NOT EXISTS operating_name text,
  ADD COLUMN IF NOT EXISTS primary_contact_title text,
  ADD COLUMN IF NOT EXISTS billing_contact_name text,
  ADD COLUMN IF NOT EXISTS billing_contact_email text,
  ADD COLUMN IF NOT EXISTS billing_contact_phone text,
  ADD COLUMN IF NOT EXISTS accounts_payable_email text,
  ADD COLUMN IF NOT EXISTS preferred_billing_method text,
  ADD COLUMN IF NOT EXISTS requires_po_number boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS site_contact_name text,
  ADD COLUMN IF NOT EXISTS site_contact_phone text,
  ADD COLUMN IF NOT EXISTS site_contact_email text,
  ADD COLUMN IF NOT EXISTS project_notes text,
  ADD COLUMN IF NOT EXISTS billing_address_line_1 text,
  ADD COLUMN IF NOT EXISTS billing_city text,
  ADD COLUMN IF NOT EXISTS billing_province text,
  ADD COLUMN IF NOT EXISTS billing_postal_code text,
  ADD COLUMN IF NOT EXISTS billing_address_same_as_service boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS portal_access_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS preferred_communication_method text DEFAULT 'Email',
  ADD COLUMN IF NOT EXISTS customer_tags text[],
  ADD COLUMN IF NOT EXISTS referral_source text;
