ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Maintenance & Repairs';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Property Care & Landscaping';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Electrical';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Plumbing';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Carpentry & Renovations';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Roofing & Exteriors';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Painting & Finishing';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Heating, Ventilation & Air Conditioning';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Concrete & Masonry';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Security & Smart Home';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Fencing & Decking';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Tiling & Flooring';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Gutter Cleaning & Repair';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Window Cleaning';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Pest Control';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Moving & Hauling';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Insulation & Drywall';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Appliance Install & Repair';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Garage Doors';
ALTER TYPE public.service_category ADD VALUE IF NOT EXISTS 'Locksmith Services';