
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_leases TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_maintenance_activity TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_maintenance_request_attachments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_maintenance_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_managed_properties TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_owner_properties TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_property_owners TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_documents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_emergency_contacts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_inspections TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_insurance TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_ledger TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_notices TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_occupants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_pets TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_referrals TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenant_vehicles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_tenants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_units TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_work_order_attachments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pm_work_orders TO authenticated;

GRANT ALL ON public.pm_leases TO service_role;
GRANT ALL ON public.pm_maintenance_activity TO service_role;
GRANT ALL ON public.pm_maintenance_request_attachments TO service_role;
GRANT ALL ON public.pm_maintenance_requests TO service_role;
GRANT ALL ON public.pm_managed_properties TO service_role;
GRANT ALL ON public.pm_owner_properties TO service_role;
GRANT ALL ON public.pm_property_owners TO service_role;
GRANT ALL ON public.pm_tenant_documents TO service_role;
GRANT ALL ON public.pm_tenant_emergency_contacts TO service_role;
GRANT ALL ON public.pm_tenant_inspections TO service_role;
GRANT ALL ON public.pm_tenant_insurance TO service_role;
GRANT ALL ON public.pm_tenant_ledger TO service_role;
GRANT ALL ON public.pm_tenant_notices TO service_role;
GRANT ALL ON public.pm_tenant_occupants TO service_role;
GRANT ALL ON public.pm_tenant_pets TO service_role;
GRANT ALL ON public.pm_tenant_referrals TO service_role;
GRANT ALL ON public.pm_tenant_vehicles TO service_role;
GRANT ALL ON public.pm_tenants TO service_role;
GRANT ALL ON public.pm_units TO service_role;
GRANT ALL ON public.pm_work_order_attachments TO service_role;
GRANT ALL ON public.pm_work_orders TO service_role;
